bg_img_link: "bong-da.jpg"
user:
  password:
  #password < 9 ky tu, phai chua chu cai vao so va ky tu dac biet
    regex: !ruby/regexp /(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[\W]).{8,}/
  email:
    regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+/
  phone:
  #regex sdt viet nam
    regex: !ruby/regexp /(84|0[3|5|7|8|9])+([0-9]{8})\b/
  user_url: "https://secure.gravatar.com/avatar/#{gravatar_id}"
digits:
  length_10: 10
  length_30: 30
soccer_field:
  rate_default: 3
  price_step: 10000
  price_default: 200000
  field_type: [5, 7, 9, 11]
  rate: [1,2,3,4,5]
image:
  avatar:
    size: 50
  soccer_field:
    size: 100
  type: ["image/jpeg", "image/gif", "image/png"]
  size: 5
  resize_to_limit: [200, 100]
  resize_to_limit_preview: [200, 100]
  accept_path: "image/jpeg, image/gif, image/png"
